stages:
  load:
    cmd: python load.py
    deps:
    - load.py
    params:
    - data_load
    - raw_data
    outs:
    - data/interim/metadata.csv
  train:
    cmd: python train.py
    deps:
    - data/interim/metadata.csv
    - model_utils.py
    - train.py
    params:
    - data_load
    - train
    - wandb
    outs:
    - models/
