raw_data:
  excel_path: "/kaggle/input/datasets/qwidermesmoudi2025/demographic/oasis_longitudinal_demographics-8d83e569fa2e2d30.xlsx"
  base_paths:
    - "/kaggle/input/datasets/qwidermesmoudi2025/oasis2-raw/OAS2_RAW_PART1/OAS2_RAW_PART1"
    - "/kaggle/input/datasets/qwidermesmoudi2025/oasis2-raw/OAS2_RAW_PART2/OAS2_RAW_PART2"
  img_relative_path: "RAW/mpr-1.nifti.img"

data_load:
  metadata_path: "data/interim/metadata.csv"
  img_size: 224
  num_slices: 50
  n_splits: 5
  random_state: 42
  output_path: "data/interim/metadata.csv"
  columns:
    - "Subject ID"
    - "MRI ID"
    - "CDR"

train:
  learning_rate: 0.0001
  weight_decay: 0.00001
  batch_size: 2
  epochs: 30
  patience: 7
  backbone: "efficientnet_b0"
  model_save_path: "models/"

wandb:
  project: "mri-alzheimer-classification"
  name: "3d-cnn-baseline"

 